version: '3.6'

services:
  fast_api:
    build:
      context: .
      args:
        - DATABASE_IP=$DATABASE_IP
    ports:
    - "12333:12333"
    volumes:
    - /nfs:/nfs:shared
    container_name: fast_api
    network_mode: "default"
    restart: 'always'